import { StyleSheet } from 'react-native';
import Colors from '../../../helpers/Colors';

const styles = StyleSheet.create({
  body: {
    backgroundColor: Colors.secondary,
  },
  container: {
    height: 500,
    width: '100%',
    marginBottom: 100,
    position: 'relative',
    flex: 2,
  },
  img: {
    flex: 1,
    width: null,
    height: null,
    resizeMode: 'cover',
  },
  info:{
    position: 'absolute',
    height: 100,
    width: 250,
    backgroundColor: 'white',
    bottom: -70,
    left: '50%',
    translateX: -(250 / 2),
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: Colors.darkGrey,
    shadowOffset: { width: 2, height: 5 },
    shadowOpacity: 0.2,
    // shadowRadius: 2,
    elevation: 5,
    },
    ratings: {
        padding: 10,
    },
    tags: {
        marginTop: 5,
        marginBottom: 5,
        flexDirection: 'row',
        justifyContent: 'space-between',
        // display: 'flex',
    },
    tag: {
        padding: 3,
        paddingLeft: 8,
        paddingRight: 8,
        backgroundColor: Colors.primary,
        color:'white',
        borderRadius: 20,
        fontSize: 10,
    },
    rate:{
        flexDirection: 'row',
        marginTop: 5,
        alignItems: 'center',
    },
    star:{
        marginLeft: 5,
        marginTop: 2,
    },
    half:{
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
        bottom: 250,
        borderWidth: 0.5,
    },
    next: {
        width: 60,
        height: 60,
        right: '50%',
        borderRadius: 60 / 2,
        translateX: 60 / 2,
        translateY: 60 / 2,
        backgroundColor: Colors.primary,
        borderColor: Colors.primary,
        zIndex: 3,
      },
      middle:{
        width: 80,
        height: 80,
        right: '50%',
        borderRadius: 80 / 2,
        translateX: 80 / 2,
        translateY: 80 / 2,
        backgroundColor: 'rgba(19, 183, 255, 0.7)',
        borderColor: 'rgba(19, 183, 255, 0.7)',
        zIndex: 2,
      },
      lowest:{
        width: 100,
        height: 100,
        right: '50%',
        borderRadius: 100 / 2,
        translateY: 100 / 2,
        translateX: 100 / 2,
        backgroundColor: 'rgba(19, 183, 255, 0.5)',
        borderColor: 'rgba(19, 183, 255, 0.5)',
        zIndex: 1,
        },
        goBack: {
          position: 'absolute',
          top: 10,
          left: 10,
        },
        talkBox: {
         paddingLeft: 30,
         paddingRight: 30,
         marginBottom: 100,
        },
        talk: {
          textAlign: 'justify',
        },
        bookBox: {
          position: 'absolute',
          padding: 15,
          alignItems: 'center',
          justifyContent: 'center',
          right: 30,
          bottom: 30,
          backgroundColor: Colors.primary,
          borderColor: Colors.primary,
          borderTopLeftRadius: 20,
          borderBottomRightRadius: 20,
          shadowColor: Colors.darkGrey,
          shadowOffset: { width: 2, height: 5 },
          shadowOpacity: 0.2,
          elevation: 5,
        },
        book:{
          color: 'white',
        },
});

export default styles;
